# Generated by Django 5.2.14 on 2026-05-18 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nume', models.CharField(max_length=30)),
                ('prenume', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=40)),
                ('parola', models.CharField(max_length=32)),
                ('tip_persoana', models.CharField(max_length=10)),
                ('companie', models.CharField(blank=True, max_length=60, null=True)),
                ('adresa', models.CharField(max_length=150)),
                ('status_cos', models.BooleanField()),
                ('lat', models.FloatField(blank=True, null=True)),
                ('lon', models.FloatField(blank=True, null=True)),
            ],
        ),
    ]
